name: Deploy Personal_Backend


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  release:
    types: [published]
  push:
    branches: [ "master" ]
      
jobs:
  deploy-docker-personal:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
        
        - uses: actions/checkout@v3
        - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ matrix.dotnet-version }}
        
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build --configuration Release --no-restore
        - name: Test
          run: dotnet test --no-restore --verbosity normal

        - uses: actions/checkout@v3
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4.1.1
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            flavor: latest = true
            tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr
              type=semver,pattern=v{{version}}
              type=semver,pattern=v{{major}}.{{minor}}
              type=semver,pattern=v{{major}}
              type=sha

        - name: Login to image repository
          uses: docker/login-action@v2.1.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        

        - name: Build and push
          uses: docker/build-push-action@v3.2.0
          with:
            context: ./personal/
            file: .personal/Dockerfile
            push: ${{ github.ref_type != 'pull_request' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            

